using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TriviaClient.Callbacks
{
    interface IGameCallback
    {
        /// <summary>
        /// Sends when the player clicks the "ready" button.
        /// </summary>
        public void sendReady();

        /// <summary>
        /// Sends the answer the player has supplied.
        /// </summary>
        /// <param name="player_id">The unique id of the player.</param>
        /// <param name="answer">The answer the player provided.</param>
        public void sendAnswer(int player_id, int answer);

        /// <summary>
        /// Receives and saves the unique id the player has give to the system.
        /// </summary>
        public void receiveId();

        /// <summary>
        /// Gets the signal from the server to start a game.
        /// </summary>
        public void startGame();

        /// <summary>
        /// Receives the question from the server.
        /// </summary>
        /// <param name="question">The question generated by the server.</param>
        public void receiveQuestion(Question question);

        /// <summary>
        /// Sends if the player wants to restart the game.
        /// </summary>
        public void sendRestart();

        /// <summary>
        /// Sends if a player wants to leave a game.
        /// </summary>
        public void sendLeave();
    }
}
